apiVersion: batch/v1
kind: Job
metadata:
  name: artillery-load-test
  namespace: observability
spec:
  # If fail, avoid loop
  backoffLimit: 0 
  template:
    spec:
      containers:
        - name: artillery
          image: artilleryio/artillery:2.0.0-31 
          args:
            - "run"
            - "/scripts/load-test.yml"
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      restartPolicy: Never 
      volumes:
        - name: script-volume
          configMap:
            name: artillery-config
